### ISSUE TITLE
Using mix_systemd in one-off release eval

### ISSUE THREAD

**Issue by yuchunc** [cogini/mix_systemd#1]
Hi Jake,

I am thinking about using mix_systemd in one-off release eval. So we can build a non-local release, put it on to the server, and run the one-off commands on the server.
What do you think?

Also I think `Mix.Tasks.Systemd` can be move in to `lib/`.  
https://github.com/yuchunc/mix_systemd/blob/master/lib/mix_systemd/utils.ex

**Comment by reachfh** [comment]
mix_systemd is fine for just generating the systemd unit file, all by itself. It doesn't need to be used in conjunction with mix_deploy.  You will still probably want to have some scripts that run as startup to do e.g. migrations, so mix_systemd is useful. I use them together with deployments via Ansible to dedicated servers, which sounds similar. https://galaxy.ansible.com/cogini/elixir-release
I would be interested to add your use case if it's not already supported. 

While the module could be put directly in lib, editors like vim expect that there is a directory hierarchy, so I can e.g. put the cursor on MixSystemd.Utils and type 'gf' and it will load the file in a buffer.

**Comment by yuchunc** [comment]
I am overcomplicating the issue.
Copying the generating systemd in to release is much simpler.
